// <auto-generated />
namespace EntityFramework_CodeFirst_Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RefatoradoCategoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefatoradoCategoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201808121458113_RefatoradoCategoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
